server:
  port: 8084

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    hostname: localhost

spring:
  application:
    name: Division Service
#    zipkin:
#      base-url: http://127.0.0.1:9411/zipkin/
#      enabled: true
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  #    loadbalancer:
  #      zone: default
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect


logging:
  file: E:\Tofazzal\Practice\Spring-cloud-microservice\department-sevice\log\zipkin-microservice.log