server:
  port: 8182

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: REDIS-SERVICE
    sleuth:
      tracing:
        enabled: true
      sampler:
        probability: 1.0 # Always sample traces for development/testing


  redis:
    host: localhost
    port: 6379
    password: null
    timeout: 2000
    database: 0
    ssl: false
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        min-idle: 0
        max-idle: 8


  #remote-fields: headers to propagate across services
  #correlation-fields: headers to log via MDC (so you can see them in logs
  sleuth:
    propagation:
      type: w3c
    baggage:
      remote-fields: X-Correlation-Id
      correlation-fields: X-Correlation-Id



#Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always