apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  replicas: 3 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: tofazzal/user-service.jar:latest
          # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
# The port that the container is running on in the cluster

---
apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: user-service-svc
spec:
  selector:
    app: user-service
  ports:
    - protocol: "TCP"
      port: 8081 # The port that the service is running on in the cluster
      targetPort: 8081 # The port exposed by the service
  type: NodePort # type of the service.